### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Greeenman999** [Greeenman999/LibrarianTradeFinder#40]
This is an issue with my current todo list for this project. 

- [ ] Support Latest MC Version
- [ ] UI Fields don't work everytime
- [ ] Legit Mode: Slow Search
- [ ] Action Trade Found
- [ ] Swing Offhand on Lectern Place
